### ISSUE TITLE
Slides for dAppcon, Berlin 2023

### ISSUE THREAD

**Issue by moul** [gnolang/workshops#26]
Draft started here: #25 

**Date:** Sep 11-13, 2023

[dappcon.io](https://www.dappcon.io/)

**Comment by roethke** [comment]
Working with Valeh on Title + Description, [Notion page here](https://www.notion.so/allinbits/DappCon-Keynote-845068c5711b42bf8cf2a419ad95621c).

**Comment by roethke** [comment]
[Draft](https://docs.google.com/presentation/d/12m672l_GoPb5Mf41rSMSfIn_c0RqFTstbzAeL9yq8TY/edit#slide=id.p) shared with Marketing team.

**Comment by moul** [comment]
Done, thank you.
