### ISSUE TITLE
Create an official "hackmd" theme

### ISSUE THREAD

**Issue by moul** [gnolang/workshops#29]
In line with item #12, this is specifically for presentations crafted in Hackmd.

@thehowl, would you be able to share some slides?

I've initially assigned @alexiscolin and @gnolang/devrels for a follow-up. However, please adjust the assignment as you see fit.

**Comment by roethke** [comment]
Respectfully, I would like to delegate this task to the design department to manage so that devrel can focus on attracting and retaining developers through technical documentation efforts.
